use std::sync::atomic::{AtomicI32, Ordering};

use crate::api::GcTracedNodeClass;

static FINALIZER_COUNT: AtomicI32 = AtomicI32::new(0);

/// RIDL class `GcTracedNode`: a JS-visible object whose opaque holds a
/// `Traced<Value>` field. The gc_mark callback (auto-generated by RIDL)
/// marks this field during GC, keeping the referenced JS object alive
/// while the GcTracedNode is reachable.
pub struct DefaultGcTracedNode {
    pub held: Option<mquickjs_rs::Traced<mquickjs_rs::Value>>,
}

impl DefaultGcTracedNode {
    pub fn new() -> Self {
        Self { held: None }
    }
}

impl Drop for DefaultGcTracedNode {
    fn drop(&mut self) {
        FINALIZER_COUNT.fetch_add(1, Ordering::SeqCst);
    }
}

impl GcTracedNodeClass for DefaultGcTracedNode {
    fn finalizer_count(&mut self) -> i32 {
        FINALIZER_COUNT.load(Ordering::SeqCst)
    }

    fn gc_mark(&self, mf: *const mquickjs_rs::mquickjs_ffi::JSMarkFunc) {
        if let Some(ref held) = self.held {
            unsafe { held.gc_mark(mf) };
        }
    }
}
