pub mod impls {
    pub use crate::generated::impls::ConsoleSingleton;

    pub use crate::stdlib_impl::create_console_singleton;
    pub use crate::stdlib_impl::ridl_console_vtable_create;
    pub use crate::stdlib_impl::DefaultConsoleSingleton;

    // v1 glue expects these names in crate::impls::*.
    pub use crate::stdlib_impl::rust_console_error;
    pub use crate::stdlib_impl::rust_console_get_enabled;
    pub use crate::stdlib_impl::rust_console_log;
}

// Erased singleton vtables consumed by the app-side aggregated ridl_context_init.
pub static RIDL_CONSOLE_SINGLETON_VT: mquickjs_rs::ridl_runtime::RidlErasedSingletonVTable =
    mquickjs_rs::ridl_runtime::RidlErasedSingletonVTable {
        create: ridl_console_singleton_create,
        drop: ridl_console_singleton_drop,
    };

unsafe extern "C" fn ridl_console_singleton_create() -> *mut core::ffi::c_void {
    let b: Box<dyn impls::ConsoleSingleton> = impls::create_console_singleton();
    // Store a pointer to the Box (thin pointer), so it can round-trip through c_void safely.
    Box::into_raw(Box::new(b)) as *mut core::ffi::c_void
}

unsafe extern "C" fn ridl_console_singleton_drop(p: *mut core::ffi::c_void) {
    if !p.is_null() {
        let holder: Box<Box<dyn impls::ConsoleSingleton>> = Box::from_raw(p as *mut _);
        drop(holder);
    }
}

#[path = "../stdlib_impl.rs"]
mod stdlib_impl;

mod __ridl_module_api {
    include!(concat!(env!("OUT_DIR"), "/ridl_module_api.rs"));
}

pub use __ridl_module_api::{initialize_module, ridl_module_context_init};

// Re-export glue symbols for C side registration / lookup if needed.
mod generated {
    pub mod glue {
        include!(concat!(env!("OUT_DIR"), "/stdlib_glue.rs"));
    }
    pub mod symbols {
        include!(concat!(env!("OUT_DIR"), "/stdlib_symbols.rs"));
    }
    pub mod impls {
        include!(concat!(env!("OUT_DIR"), "/stdlib_impl.rs"));
    }

    // shared across modules: generated by the app build.rs and included into the app crate.
    // RIDL module crates must not define their own ctx_ext.
}

pub use generated::glue::*;