/****************************************************************************
 * ports/openvela/app/js_main.c
 *
 * NSH builtin: run JS scripts with the mquickjs engine on OpenVela/NuttX sim.
 *
 * Usage: js <script.js> [<script2.js> ...]
 *
 * Output protocol (sentinel lines, scanned by the host-side runner — NSH
 * builtins have no scriptable exit code):
 *   CASE <basename> PASS
 *   CASE <basename> FAIL: <message>
 *   CASES <passed>/<total> PASS     (summary line)
 *
 * Integration (see ports/openvela/README.md and the Phase 2b section of
 * docs/planning/2026/2026-10-08-openvela-port.md):
 * - SOURCE-LEVEL integration: the engine's .c files AND the ridl-variant
 *   stdlib runtime TUs (mqjs_stdlib_impl.c / mqjs_require.c from
 *   deps/mquickjs-rs, plus the app aggregate's mquickjs_ridl_register.c)
 *   are compiled by the openvela apps build with the NuttX toolchain, so
 *   every libc binding (setjmp/longjmp, malloc/free) stays on the NuttX
 *   side. `js_stdlib` (strong, RIDL tables incl. console) is defined by
 *   mqjs_stdlib_impl.o — generated by the engine's own host tool from
 *   mqjs_stdlib_template.c; THIS file must not include that header.
 * - Rust adapter bridge: console (and every other RIDL export) is served
 *   by the Rust stdlib module via the adapter staticlib. The JSContext
 *   itself must be created by the Rust side — mquickjs has no runtime
 *   registration API and the RIDL glue dispatches through the Context
 *   user_data that only mquickjs_rs::Context::new installs — so this file
 *   uses the adapter trio (mqjs_rs_ridl_context_new / mqjs_rs_ridl_eval /
 *   mqjs_rs_ridl_context_free) instead of JS_NewContext/JS_Eval directly.
 *   The Rust side owns the engine heap block and frees it on context_free;
 *   there is no C-side malloc for the JS heap anymore.
 * - The rs probe functions (rsVersion/rsSelfTest) are baked into the
 *   generated stdlib table by the staged generator overlay (setup-sim.sh
 *   step 1b, now on mqjs_stdlib_template.c). Their definitions live HERE
 *   and are non-static: the generated table references them from
 *   mqjs_stdlib_impl.o (a different TU).
 ****************************************************************************/

/****************************************************************************
 * Included Files
 ****************************************************************************/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "mquickjs.h"

/****************************************************************************
 * Pre-processor Definitions
 ****************************************************************************/

/* JS heap for the script contexts. 2 MiB is ample for the case corpus on
 * sim; the block itself is allocated and owned inside the Rust adapter. */

#define JS_HEAP_SIZE (2 * 1024 * 1024)

/* Error text buffer for the eval result (NUL byte included). */

#define JS_ERRBUF_SIZE 256

/****************************************************************************
 * Rust adapter bridge (libmqjs_openvela_adapter.a, staged into apps/staging
 * by setup-sim.sh).
 *
 * mqjs_rs_ridl_context_new runs the process-level RIDL bootstrap once,
 * creates the Context (engine heap via the image's malloc through the Rust
 * allocator), initializes the per-context RIDL state (ridl_context_init)
 * and runs the C-side JS_RIDL_StdlibInit (provided by the aggregate's
 * mquickjs_ridl_register.c compiled into this image). Returns NULL on
 * failure.
 ****************************************************************************/

extern void *mqjs_rs_ridl_context_new(unsigned long heap_bytes);
extern void mqjs_rs_ridl_context_free(void *ctx);
extern int mqjs_rs_ridl_eval(void *ctx, const unsigned char *script,
                             unsigned long len, unsigned char *err_buf,
                             unsigned long err_cap);

/* The generated stdlib table (in mqjs_stdlib_impl.o) references these —
 * the compile-time registration overlay in setup-sim.sh step 1b. */

extern const char *mqjs_rs_version(void);
extern int mqjs_rs_self_test(void);

JSValue js_rs_version(JSContext *ctx, JSValue *this_val, int argc,
                      JSValue *argv)
{
    /* Static NUL-terminated string owned by the adapter; JS_NewString copies
     * it into the JS heap (tracing GC) — nothing to free here. */
    return JS_NewString(ctx, mqjs_rs_version());
}

JSValue js_rs_self_test(JSContext *ctx, JSValue *this_val, int argc,
                        JSValue *argv)
{
    /* Runs a full Rust-side Context (2 MiB), evals "1+1", drops it;
     * 0 on success. */
    return JS_NewInt32(ctx, mqjs_rs_self_test());
}

/****************************************************************************
 * Case runner
 ****************************************************************************/

static char *read_file(const char *path, size_t *len_out)
{
    FILE *f;
    char *buf;
    long len;

    f = fopen(path, "rb");
    if (f == NULL)
    {
        return NULL;
    }

    if (fseek(f, 0, SEEK_END) != 0 || (len = ftell(f)) < 0)
    {
        fclose(f);
        return NULL;
    }
    rewind(f);

    buf = malloc((size_t)len + 1);
    if (buf == NULL)
    {
        fclose(f);
        return NULL;
    }

    if (len > 0 && fread(buf, 1, (size_t)len, f) != (size_t)len)
    {
        free(buf);
        fclose(f);
        return NULL;
    }
    fclose(f);

    buf[len] = '\0';
    *len_out = (size_t)len;
    return buf;
}

static const char *basename_of(const char *path)
{
    const char *slash = strrchr(path, '/');
    return slash != NULL ? slash + 1 : path;
}

/* Some editors add a UTF-8 BOM; QuickJS doesn't accept it. */

static void strip_bom(char *buf, size_t *len)
{
    if (*len >= 3 && (unsigned char)buf[0] == 0xef
        && (unsigned char)buf[1] == 0xbb && (unsigned char)buf[2] == 0xbf)
    {
        *len -= 3;
        memmove(buf, buf + 3, *len + 1);
    }
}

static int run_case(const char *path)
{
    const char *name = basename_of(path);
    size_t len;
    char *buf;
    void *ctx;
    unsigned char errbuf[JS_ERRBUF_SIZE];
    int failed;

    buf = read_file(path, &len);
    if (buf == NULL)
    {
        printf("CASE %s FAIL: cannot read file\n", name);
        return 1;
    }
    strip_bom(buf, &len);

    ctx = mqjs_rs_ridl_context_new(JS_HEAP_SIZE);
    if (ctx == NULL)
    {
        printf("CASE %s FAIL: ridl context create failed\n", name);
        free(buf);
        return 1;
    }

    failed = mqjs_rs_ridl_eval(ctx, (const unsigned char *)buf, len,
                               errbuf, sizeof(errbuf)) != 0;
    if (!failed)
    {
        printf("CASE %s PASS\n", name);
    }
    else
    {
        /* The adapter reports the JS exception text (JS_GetException ->
         * JS_ToCString on the Rust side), covering thrown strings,
         * primitives and SyntaxError — same text the direct C path
         * produced in Phase 1. */

        printf("CASE %s FAIL: %s\n", name,
               errbuf[0] != '\0' ? (const char *)errbuf
                                 : "<unprintable error>");
    }

    mqjs_rs_ridl_context_free(ctx);
    free(buf);
    return failed ? 1 : 0;
}

/****************************************************************************
 * Public Functions
 ****************************************************************************/

int js_main(int argc, char **argv)
{
    int i;
    int total;
    int passed;

    if (argc < 2)
    {
        printf("usage: js <script.js> [<script2.js> ...]\n");
        return 2;
    }

    total = argc - 1;
    passed = 0;
    for (i = 1; i < argc; i++)
    {
        passed += run_case(argv[i]) == 0 ? 1 : 0;
    }

    printf("CASES %d/%d PASS\n", passed, total);
    return passed == total ? 0 : 1;
}
