#!/usr/bin/env bash
# ports/openvela/setup-sim.sh — idempotent setup of the mquickjs `js` builtin
# in an OpenVela/NuttX sim tree, then build.
#
# Usage:
#   ports/openvela/setup-sim.sh build          # Make 轨
#   ports/openvela/setup-sim.sh build-cmake    # CMake 轨
#   OPENVELA_DIR env var overrides the openvela tree (default ~/workspace/openvela).
#
# 非侵入原则（2026-10-09 用户裁定）：移植适配不得修改 openvela 树的公共基础
# 设施（defconfig / Kconfig / 构建脚本 / external 内容）。对 openvela 树的
# 全部写入仅限两类：
#   1. apps/system/mqjs 符号链接（apps 树的标准应用接入点，纯新增）
#   2. 构建产物目录（nuttx/ 的 .config 与目标文件、cmake_out/——均为
#      可再生成的构建状态，非受跟踪内容）
# 其余一切适配物（合成 defconfig、CUSTOM_MODULE_PATH 覆盖目录、atom 头、
# 引擎源 staging）都收敛在本仓库 ports/openvela/ 内。
#
# 集成模型（源码级，参照 apps/interpreters/quickjs）：引擎 .c 由 openvela
# apps 构建用 NuttX 工具链编译，libc 绑定全部一致落在 NuttX 侧；引擎自身
# 工具链（mqjs_stdlib host 工具）负责 atom 表等宿主代码生成。
#
# 双轨互斥：Make 轨与 CMake 轨共用同一 nuttx 树，切换方向需先
# distclean（Make→CMake 由本脚本自动执行；CMake→Make 由 configure 触发）。
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OPENVELA="${OPENVELA_DIR:-$HOME/workspace/openvela}"
ENGINE_SRC="$REPO_ROOT/deps/mquickjs"
APP_DIR="$REPO_ROOT/ports/openvela/app"
GEN_DIR="$APP_DIR/gen"
ENGINE_STAGE="$APP_DIR/engine_src"
CMAKE_OVERRIDE_DIR="$REPO_ROOT/ports/openvela/cmake"
COMPOSITE_DEFCONFIG_DIR="$GEN_DIR/nsh"

if [ ! -d "$OPENVELA/nuttx" ]; then
    echo "ERROR: openvela tree not found at $OPENVELA (set OPENVELA_DIR)" >&2
    exit 1
fi
if [ ! -f "$ENGINE_SRC/mquickjs.c" ]; then
    echo "ERROR: engine sources not found at $ENGINE_SRC" >&2
    exit 1
fi

# 1) app dir symlink（apps 树标准接入点，纯新增）
ln -sfn "$APP_DIR" "$OPENVELA/apps/system/mqjs"

# 2) stage engine sources + headers for the apps build
mkdir -p "$ENGINE_STAGE"
for f in mquickjs.c cutils.c dtoa.c libm.c mqjs_stdlib.c \
         mquickjs.h mquickjs_priv.h cutils.h dtoa.h libm.h list.h; do
    cp -f "$ENGINE_SRC/$f" "$ENGINE_STAGE/$f"
done

# 3) engine-native host toolchain: build the mqjs_stdlib host tool and
#    generate the atom-table headers (mirrors deps/mquickjs/Makefile rules)
mkdir -p "$GEN_DIR"
HOST_FLAGS="-O2 -D_GNU_SOURCE -fno-math-errno -fno-trapping-math -I$ENGINE_SRC"
cc $HOST_FLAGS -c "$ENGINE_SRC/mqjs_stdlib.c" -o "$GEN_DIR/mqjs_stdlib.host.o"
cc $HOST_FLAGS -c "$ENGINE_SRC/mquickjs_build.c" -o "$GEN_DIR/mquickjs_build.host.o"
cc $HOST_FLAGS -o "$GEN_DIR/mqjs_stdlib" \
    "$GEN_DIR/mqjs_stdlib.host.o" "$GEN_DIR/mquickjs_build.host.o"
"$GEN_DIR/mqjs_stdlib" -a > "$GEN_DIR/mquickjs_atom.h"
"$GEN_DIR/mqjs_stdlib" > "$GEN_DIR/mqjs_stdlib.h"
echo "atom headers generated: $GEN_DIR/mquickjs_atom.h mqjs_stdlib.h"

# 4) composite defconfig（合成：openvela sim:nsh defconfig + 本移植片段）
#    目录形态必须为 <config>/defconfig（NuttX cmake 按
#    NUTTX_DEFCONFIG = <BOARD_CONFIG>/defconfig 解析），生成到本仓库
#    gen/，不动 openvela 的 defconfig。
BASE_DEFCONFIG="$OPENVELA/nuttx/boards/sim/sim/sim/configs/nsh/defconfig"
if [ ! -f "$BASE_DEFCONFIG" ]; then
    echo "ERROR: base defconfig not found at $BASE_DEFCONFIG" >&2
    exit 1
fi
mkdir -p "$GEN_DIR/nsh"
cp "$BASE_DEFCONFIG" "$GEN_DIR/nsh/defconfig"
cat >> "$GEN_DIR/nsh/defconfig" <<'EOF'

# mquickjs js builtin (ports/openvela) — composite defconfig, not in-tree
CONFIG_MQJS_JS=y
CONFIG_FS_HOSTFS=y
CONFIG_BOARDCTL=y
EOF

# 5) framework.mk（Make 轨消费的机器本地路径；CMake 轨直接用 gen/ 合成
#    defconfig，无需单独文件）
cat > "$APP_DIR/framework.mk" <<EOF
# Generated by ports/openvela/setup-sim.sh — do not commit.
MQJS_GEN_DIR := $GEN_DIR
MQJS_ENGINE_SRC := $ENGINE_SRC
EOF

# 6) build
MODE="${1:-}"
case "$MODE" in
"build")
    cd "$OPENVELA/nuttx"
    if [ ! -f .config ]; then
        ./tools/configure.sh sim:nsh
    fi
    # 片段追加到 .config（构建状态文件，非受跟踪基础设施）
    grep -q "CONFIG_MQJS_JS=y" .config || cat >> .config <<'EOF'
CONFIG_MQJS_JS=y
CONFIG_FS_HOSTFS=y
CONFIG_BOARDCTL=y
EOF
    make olddefconfig >/dev/null
    make -j"$(nproc)"
    echo "OK: $OPENVELA/nuttx/nuttx"
    ;;
"build-cmake")
    # 与已验证成功的官方序列一致（distclean → rm cmake_out → lunch 静默
    # 完成全部 cmake configure → cmake --build），唯一差异是 lunch 前导出
    # VELA_BUILD_BOARD_CONFIG 指向本仓库的合成 defconfig 目录
    # （envsetup.sh:231 会采用该值），从而零改动 openvela 树。
    # 注意：gen/nsh/defconfig 的目录形态是 NuttX cmake 的解析契约
    # （NUTTX_DEFCONFIG = <BOARD_CONFIG>/defconfig）。
    if [ -f "$OPENVELA/nuttx/Makefile" ] || [ -f "$OPENVELA/nuttx/.config" ]; then
        echo "NOTE: switching tracks — distclean (build artifacts only)"
        make -C "$OPENVELA/nuttx" distclean >/dev/null 2>&1 || true
    fi
    rm -rf "$OPENVELA/cmake_out"

    export VELA_BUILD_BOARD_CONFIG="$COMPOSITE_DEFCONFIG_DIR"
    # envsetup 不兼容 nounset：在子 shell 中关闭后执行 lunch/构建
    (
        set +eu
        cd "$OPENVELA"
        source build/envsetup.sh
        lunch sim:nsh cmake_out/sim_nsh >/dev/null
        cmake --build cmake_out/sim_nsh -j"$(nproc)"
    )
    echo "OK: $OPENVELA/cmake_out/sim_nsh/nuttx"
    ;;
*)
    echo "setup complete (pass 'build' or 'build-cmake' to also build)"
    ;;
esac
