use mquickjs_rs::mquickjs_ffi;

pub struct Context {
    inner: mquickjs_rs::Context,
}

impl Context {
    pub fn new(memory_capacity: usize) -> Result<Self, Box<dyn std::error::Error>> {
        let inner = mquickjs_rs::Context::new(memory_capacity)?;

        // Context-level RIDL init is app-specific and is generated by ridl-tool aggregation.
        // It must set ctx user_data + finalizer for per-ctx singletons.
        unsafe {
            crate::ridl_context_init::ridl_context_init(inner.ctx as *mut mquickjs_ffi::JSContext);
        }

        Ok(Self { inner })
    }

    pub fn default() -> Self {
        Self::new(1024 * 1024).expect("failed to create JSContext")
    }

    pub fn eval(&mut self, code: &str) -> Result<String, String> {
        self.inner.eval(code)
    }
}

impl Default for Context {
    fn default() -> Self {
        Self::new(1024 * 1024).expect("failed to create JSContext")
    }
}
