// This module is generated by ridl-tool into OUT_DIR.
// It provides context-level initialization (per-JSContext) and must remain separate from
// process-level symbol keep-alive.
include!(concat!(env!("OUT_DIR"), "/ridl_context_init.rs"));
