// This module is generated by ridl-tool into OUT_DIR.
// It provides runtime support for RIDL extensions, including per-JSContext initialization.
pub mod ridl_runtime_support {
    include!(concat!(env!("OUT_DIR"), "/ridl_runtime_support.rs"));
}

pub use ridl_runtime_support::*;
