// This module is generated by ridl-tool into OUT_DIR.
// It provides runtime support for RIDL extensions, including per-JSContext initialization.
pub mod ridl_context_ext {
    include!(concat!(env!("OUT_DIR"), "/ridl_context_ext.rs"));
}

pub use ridl_context_ext::*;
